### ISSUE TITLE
Change on/off button from toggle to 2 buttons

### ISSUE THREAD

**Issue by dudeofawesome** [eliotstocker/Light-Controller#13]
The issue with the toggle is that it doesn't necessarily start in sync with the bulb's state, and we don't have a function that can actually toggle the bulb's state.  I think that it would be more transparent for the user to be able to be able to set the bulb's state the same way we have to with code.  (Also, the widget already uses this format.)

**Comment by eliotstocker** [comment]
Hey Everyone, can i get some votes on this?

**Comment by mrwhale** [comment]
Yeah I'd be more inclined to go with the 2 buttons, instead of toggle. There is me and my wife using the app, so the app can go out of sync with the bulb state pretty quickly, so you end up having to press the button a few times anyways. I mainly use the widgets, but on the occasion that I am in the app this is what happens

**Comment by AppLamp-API** [comment]
i like the toggle but the hardware doesn't allow state... and there's also folks that use the remote control, and then there's the wall switch, which on power off/power on, will light the bulb again, even if it was in off-state... so yeah... on/off buttons I guess

**Comment by eliotstocker** [comment]
I'm gonna call that unanimous unless anyone else cares to chime in, I'll schedule that in for the next release :)

**Comment by nagelm** [comment]
+1 for 2 buttons. My household has multiple users and shortly a [Ninja Sphere!](https://ninjablocks.com/#home/)

**Comment by eliotstocker** [comment]
Added in next beta, will update in the beta channel later today or tomorrow
