### ISSUE TITLE
Contributor Names

### ISSUE THREAD

**Issue by eliotstocker** [eliotstocker/Light-Controller#19]
Hey guys, id like to add you to the contributors list for the next release,
can @mrwhale, @myntath and @AppLamp-API give me how you would like your names displayed in the contributors list?

**Comment by mrwhale** [comment]
Awesome :)
ummmm.. yeah I think I'd prefer my real name down on that - Harry Sibenaler

Thanks man!

**Comment by nagelm** [comment]
On the off chance that you meant me (@nagelm) instead of myntath, my name is Matthew Nagel. :)

**Comment by eliotstocker** [comment]
sorry @nagelm (not paying enough attention) completely missed you off of the list, will add you for the release also :)

**Comment by eliotstocker** [comment]
closing for house keeping before release 1.6
