### ISSUE TITLE
Issue if using autodetection [BUG]

### ISSUE THREAD

**Issue by mrwhale** [eliotstocker/Light-Controller#21]
If using auto wifi bridge detection (i.e. install the app and don't touch the controller IP in settings) it works fine until you open the settings menu. Then I can't control the lights anymore until I manually change the IP to the actual IP

I did a fresh install, and everything was working fine. It was auto detecting wifi controller and I could turn things on and off. I went into settings to change the labels on the zones, and when I got out of settings I couldn't turn lights on and off anymore. I am going to assume that once you go into settings and change stuff it will save everything in there and then start using that "saved' information (the default IP) instead of autodetecting again

My network is a 10.1.1.0/24 network, and  my controller is 10.1.1.23

**Comment by eliotstocker** [comment]
Ill lookinto it as soon as i get a minute :)

**Comment by LimitlessLED** [comment]
Hi Eliot,

 

You can add a feature in the settings that lets you set the fixed IP address of the wifi bridge.  use auto detect to list all the wifi bridges on the network, and then enter a fixed ip for that particular wifi bridge.

 

Also a lot of homes have 2 or more wifi bridges… the auto detect should work when there is 2 or more wifi bridges in the home. i.e.  each button has a particular wifi bridge mac address stored against it (not ip address)

 

I have done this in the LimitlessLED Android app before if you need sample code. I am an Android developer too.

 

Regards,

Hamish.

-LimitlessLED

www.limitlessled.com

**Comment by eliotstocker** [comment]
hey @LimitlessLED that sounds very interesting :) i will have a think about the user experience for that thanks for the info id love to see some sample code at somepoint, feel free to email me on eliot (at) piratemedia.tv :)

thanks for the info

**Comment by eliotstocker** [comment]
Will definately add a way to use multiple bridges in the future, for now i have added a way to disable discovery :) hope that will resolve the main issue for now
