### ISSUE TITLE
New App

### ISSUE THREAD

**Issue by mrwhale** [eliotstocker/Light-Controller#24]
Hey guys, not an issue but thought I'd share this with everyone

Two guys have created and released a new app that does limitless/ wifi lights

https://play.google.com/store/apps/details?id=de.leethaxxs.rgbcontroller

Looks pretty neat too. Looks like they have already implemented the alarm idea this app was eventually going to have, but good to have a bit of competition :P

**Comment by eliotstocker** [comment]
always nice to see more work on these little bulbs
