### ISSUE TITLE
Blank navigation drawer in 1.6

### ISSUE THREAD

**Issue by dudeofawesome** [eliotstocker/Light-Controller#25]
The navigation drawer is blank and the toolbar is missing the open navigation drawer button.

**Comment by eliotstocker** [comment]
close the app and reopen?


—

**Comment by dudeofawesome** [comment]
That fixed both issues

**Comment by eliotstocker** [comment]
Yeah it was an upgrade issue that I missed, oops!

**Comment by dudeofawesome** [comment]
It would be good if that can be fixed for the first launch, just because a
lot of users might uninstall after the first launch if it doesn't work as
expected.

**Comment by eliotstocker** [comment]
Yeah, I can def fix it will try and bump a 1.6.1 tomorrow

**Comment by eliotstocker** [comment]
fixed in new release :)
https://github.com/eliotstocker/Light-Controller/releases/tag/v.1.6.1
