### ISSUE TITLE
Laptop broke! 

### ISSUE THREAD

**Issue by eliotstocker** [eliotstocker/Light-Controller#27]
Hey guys, I was working on the api today when my screen spontaneously combusted.
Anywyas I have scheduled it in the be picked up Tuesday but will be out of action for a little while.
Not too long figers crossed.

**Comment by mrwhale** [comment]
Oh no :( Hope it can get fixed quickly!

**Comment by eliotstocker** [comment]
Yeah I'm hopeful too, I'll be using a backup from the office in the mean time but not sure I will get everything setup.

**Comment by eliotstocker** [comment]
All fixed and back to me safely! ill consider this bug fixed! hehe
