### ISSUE TITLE
Add night mode for newer rgbw bulbs

### ISSUE THREAD

**Issue by eliotstocker** [eliotstocker/Light-Controller#31]
This should be fairly simple and I would like to add it in for the next release.

**Comment by LimitlessLED** [comment]
This from the www.limitlessled.com/dev website 

 

November 2014: how to send Nightmode to RGBW lights. send a second Off command 100 ms later. the second off command is a long press.. and it is command |= 0×80. for example 46 XOR 80 = C6 > So send 460055 Wait 100ms Then send C60055. that is hex commands 46 00 55 and C6 00 55.

**Comment by mrwhale** [comment]
Here is the nightmode array for rgbw zones (0-4), this is the first byte
nightarray=("x\C1" "\xC6" "\xC8" "\xCA" "\xCC")
@LimitlessLED can confirm this is correct?

**Comment by eliotstocker** [comment]
This is done, and will be included in beta 4
