### ISSUE TITLE
Auto App updates for beta testing

### ISSUE THREAD

**Issue by LimitlessLED** [eliotstocker/Light-Controller#33]
Is there such a thing for android like TestFlight for iPhone?  whenever a new release of a build is available for testing it automatically upgrades the test app on the phone by itself after every github dev build.

Cheers,
-Hamish.

**Comment by eliotstocker** [comment]
Yeah testflight did have android support for a little bit before the apple purchase. I'll look for another solution and look to start using that :)

**Comment by mrwhale** [comment]
Can't you link a beta Google plus group with the beta app on google play? So when people sign up for the group, they then have access to the beta download via play storr

**Comment by eliotstocker** [comment]
yeah we can do that, i have used it for work a few times.

**Comment by eliotstocker** [comment]
Hi Guys i have created a google+ community for beta releases, the latest 1.7 beta is up there (with android wear) all you have to do is join and it will download the latest beta from the play store, feel free to let anyone know about it

**Comment by LimitlessLED** [comment]
The link on the google group home page does not work.

 

In order to install Light Controller Beta From the Play Store, join this community and then visit the link bellow to opt-in

 

Clicking it gives you this:

Sorry - nothing to see here.

 

There may be several reasons:

*	The app you’re looking for doesn't exist
*	or
*	the app developer is not currently running a test
*	or
*	you are not eligible to participate in the testing program.

If you received the link to this page from someone, we recommend you contact them for more information.

**Comment by mrwhale** [comment]
I think the play store might be down :( I can't even load it in a browser, not even play.google.com

**Comment by eliotstocker** [comment]
@LimitlessLED did you join the google+ community? i think you have to join before you can join the beta

**Comment by LimitlessLED** [comment]
Nice suggestion, but nope that’s not the problem..  I am definitely already a member.

 

Communities you've joined

Light Controller BETA

4 members

**Comment by eliotstocker** [comment]
I have tried few things, but can't seem to work out why it's not working for you. Anyone else got any thoughts?

**Comment by mrwhale** [comment]
Must be the third dot point displayed "you are not eligible to participate in the testing program"
Not sure what makes some ineligible though?

**Comment by eliotstocker** [comment]
As far as I could read on the playstore setup it would seem that the only elegibility is being part of the google+ community. Very strange

**Comment by LimitlessLED** [comment]
yep it works now.

"You are now a tester"

**Comment by NoonanMedia** [comment]
great :D
