### ISSUE TITLE
Android Wear

### ISSUE THREAD

**Issue by eliotstocker** [eliotstocker/Light-Controller#35]
Android wear initial version is more or less done :) check it out in the wear branch, once i have done a bit more testing i will merge back into master.

@mrwhale great work, i didn't have to do too much to get it all sorted :D

**Comment by mrwhale** [comment]
Awesome stuff!
Are you able to create a release apk for this so I can install and test :) ? The wear app will only push to the watch if its a release apk and wont do it if its a debug

Really excited for this one! :)

**Comment by eliotstocker** [comment]
latest version available here:
https://plus.google.com/u/0/communities/117265785994204078301

that should also install the android wear app, let me know how it goes

**Comment by eliotstocker** [comment]
Im going to close this for now, for further improvements and features we can open new issues :)
