### ISSUE TITLE
[Bug] Widget issue. Displays clock when re-sized to smallest

### ISSUE THREAD

**Issue by mrwhale** [eliotstocker/Light-Controller#36]
Hey Guys,
Just updated my phone back to a HTC sense ROM (Android 5.0.2, sense 6) and just noticed an issue with the widget still displaying the clock even when at its smallest size. I didn't have this issue when I was running the GPE ROM
Here's a picture for good luck
![screenshot_2015-03-09-20-03-52](https://cloud.githubusercontent.com/assets/7307429/6568067/dd7cdd4a-c725-11e4-9b53-d3224756e65b.png)

**Comment by eliotstocker** [comment]
Yeah I saw this once per twice, odd. Can you try deleting the widget and adding it back? Just want to know if it happens consistently. I think I have a fix for this either way :)

**Comment by mrwhale** [comment]
Yeah can confirm it appears every time I delete and re-add.. for both rgbw and white widgets too. Strange that it displayed properly on the GPE ROM

**Comment by eliotstocker** [comment]
This should not be sorted in v1.7 beta 3 :)

**Comment by eliotstocker** [comment]
@mrwhale is this resolved?

**Comment by mrwhale** [comment]
Yep all good now! Just had to re add the widget, but not more clock being displayed! Awesome :)

**Comment by mrwhale** [comment]
Okay I spoke tok soon, it seems to appear again after a little while...

**Comment by eliotstocker** [comment]
any improvements on beta 4?

**Comment by mrwhale** [comment]
Mhmmh nah not yet. It seems to go away for a few minutes after re-adding the widget, then appears. Getting a new phone in a few days anyways  :D so will let you know if its still happening on a different device

**Comment by eliotstocker** [comment]
arg haha, i can tweak the values a little more also :)

**Comment by mrwhale** [comment]
Okay so update on this. On my new nexus 6 this has fixed itself. But on my wife's Samsung GS4, it's just upgraded to android 5.0.1, ( previously on 4.4.4) and this issue has started to happen on her phone too :(

**Comment by eliotstocker** [comment]
ok, ill have another look at this this week, and see what i can dig up, it must be something to do with DP vs PX as it differs on different device.

**Comment by eliotstocker** [comment]
Still unable to replicate this, so I'm assuming its a device specific issue. have made another small chnage, but going to close for now. please comment if anyone else is having this issue
