### ISSUE TITLE
[Not an issue] JRebel for Android

### ISSUE THREAD

**Issue by mrwhale** [eliotstocker/Light-Controller#39]
Not sure if you guys have heard about this thing yet, but check out http://zeroturnaround.com/software/jrebel-for-android/ for android app development :)

**Comment by eliotstocker** [comment]
interesting ill have a look at that :)

**Comment by eliotstocker** [comment]
Had a quick play with this, seems kinda cool but a little to complicated for a production app as far as i can tell for now, will keep an eye and think about it for future projects :) thanks for showing me @mrwhale it really is very cool! :dancers:
