### ISSUE TITLE
Location based actions

### ISSUE THREAD

**Issue by wjbeckett** [eliotstocker/Light-Controller#4]
Would be cool to have location based actions baked into the app.

Such as turn lights on when I get home. Or more advanced like, if I'm not at home And it's 6pm turn the entrance light on.

**Comment by eliotstocker** [comment]
i will be moving this into a seperate app (or plugin kinda) that will utilise the new API #22

**Comment by eliotstocker** [comment]
anyone still interested in this check out:
https://github.com/eliotstocker/LiFi
it is a sepperate app that makes use of the API to turn lights on when you connect to a selected wifi network, not working quite yet, but the UI is mostly functional. and it shouldnt be far from here to functionality
