### ISSUE TITLE
cannot use DNS hostname to specifiy bridge IP

### ISSUE THREAD

**Issue by kfix** [eliotstocker/Light-Controller#40]
On my local LAN, i use openwrt on my router. Its built in control panel LuCI lets you define dynamic hostnames for any DHCP clients. I have my milight bridge MAC associated to "led.phx1.domain.TLD". Openwrt's dns+dhcp server (dnsmasq) allocates any free IP address to this MAC's  hostname so the user doesn't have micromanage their LAN's addressing.

Putting a hostname like that into light-controller gets a rejected IP alert.
Could this field be changed to resolve hostnames?

On my LAN, the IP for this hostname never fluxes, so it could be cached beyond its TTL, but if using a hostname provided by dyndns.org (or similar) for out-of-house remote control, the cached lookup would have to be aggressively re-validated. I guess #7 is related to this, but I only saw IPs mentioned.

**Comment by dudeofawesome** [comment]
Android uses google's DNS by default, and doesn't use the router's DNS as a
backup, so hostnames do not work.  To fix this, you can go in to wifi
settings on your device and specify that it should use the router's DNS as
the secondary DNS.

**Comment by kfix** [comment]
DHCP-issued DNS nameserver addresses have automagically worked on my tablets since KitKat 4.4.
there's no menu option to override it in settings in Lollipop either.
anyhow, Light-controller's config page says "IP address", not "IP address / Hostname"

**Comment by kfix** [comment]
GAH, i see there's a beta build with hostname support. I'll give it a try...
