### ISSUE TITLE
[Bug] Crash when selecting previous zone in scrollable menu (beta version)

### ISSUE THREAD

**Issue by mrwhale** [eliotstocker/Light-Controller#41]
Hey @eliotstocker getting a crash every time I selected the previous zone in the zone menu (beta 1.7) I haven't yet hooked this up to adb to get the crash logs but its easily duplicated. I select a zone in the zone menu to the right hand side, but when I go to select the one on the furthest left of the screen, it crashes

Here is a picture for luck

![screenshot_2015-06-19-19-27-45](https://cloud.githubusercontent.com/assets/7307429/8298146/27c66b08-19a8-11e5-933a-36570fe18bfd.png)

In this example I have selected the Entryway zone (Zone 1) but when I go to select the All White zone it crashes. It seems to be whenever you go back to select a zone in that spot on the screen

**Comment by eliotstocker** [comment]
Cool ill try and check this out. Been crazy busy with some life things but
promis I'll get this sorted soon :)

**Comment by eliotstocker** [comment]
Fixed :)
