### ISSUE TITLE
Horizontal slider buttons

### ISSUE THREAD

**Issue by Thijxx** [eliotstocker/Light-Controller#47]
I'm having a hard time to slide the horizontal sliders for Brightness and Color Temperature without sliding the entire page the buttons are on (from White 1 to White 2 for example). Maybe use a vertical slider?
Version 1.7.0 on Android

**Comment by eliotstocker** [comment]
Hmmm that's odd im not experiencing this myself, i will see what I can find out. What android version are you on?

**Comment by Thijxx** [comment]
Cyanogenmod 11 or 12

**Comment by eliotstocker** [comment]
cool, ill have a look and see if i can replicate the issue

**Comment by eliotstocker** [comment]
cant replicate, closing
