### ISSUE TITLE
Brightness slider

### ISSUE THREAD

**Issue by Thijxx** [eliotstocker/Light-Controller#49]
Version 1.7.0 on Android
Is it maybe possible to make the brightness go to 0 and then to exactly the intensity one has chosen in stead of only being able to increase/decrease by slider? This may give some strange effects :D

**Comment by eliotstocker** [comment]
When you say go to 0, do you mean off?

**Comment by eliotstocker** [comment]
Are you talking about white zones specifically? With white lights you aren't able to set a specify value, only increase or decrease the current (unknown) value. 

This is a limitation of the bulbs unfortunately. It is not a limitation of the rgbw bulbs

**Comment by Thijxx** [comment]
Yes it may be a white-zone issue. Isn;t it possible to make the unknown value known by going back to zero first? So when I set brightness to 7, you send 100 times -1 (now it's known, it's 0) and then add 7.

**Comment by eliotstocker** [comment]
the problem with this is we have to leave at least 50 ms between each call.
and there are 10 steps meaning that each time you use the slider we would
have to start with a 500ms delay to get back to 0. this has been discussed
in a previous issue, im happy to have a play with some other ideas, but i
think it need carful consideration before further work is done.

**Comment by eliotstocker** [comment]
I'm closing this as i don't see a reasonable solution to it, please comment here if anyone has further thoughts and ill reopen
