### ISSUE TITLE
Change Zone name within Zone page

### ISSUE THREAD

**Issue by Thijxx** [eliotstocker/Light-Controller#50]
Single page Zone control. Including changing the name of the zone by holding/long-pressing it on the zone page?

**Comment by eliotstocker** [comment]
Seems to me that people aren't going to be changing the zone names all that frequently, so I'm not sure this is worth implementing. 

What does everyone else think?

**Comment by mrwhale** [comment]
Yeah I'm with you on this one @eliotstocker. on first setup of the app I change the names of the zones, and have not changed them since. Unless you are constantly moving the globes around the house, I wouldn't see the need for this

**Comment by eliotstocker** [comment]
closing to clean up a little
