### ISSUE TITLE
Crashes 1.7.0

### ISSUE THREAD

**Issue by Thijxx** [eliotstocker/Light-Controller#52]
My app crashed on stock android, it's version 1.7.0, never runs for more than 5 minutes. I've sent crash reports.
it even crashes multiple times without me restarting it (!!!)
After crash, the app stops working. Need to restart wifi box, sucks bigtime.

**Comment by eliotstocker** [comment]
This is now fixed as of the build that is currently rolling out. Please let me know if your issues persists after today's update
