### ISSUE TITLE
White light zone 4 disappears

### ISSUE THREAD

**Issue by Djuke** [eliotstocker/Light-Controller#55]
I've noticed that if you disable the RGBW zones control in settings then the 4th white light zone disappears. It doesn't matter if you have tabs enabled for navigation or not. This is tested on the nexus 6 with android 6.0 and app version 1.7.

**Comment by eliotstocker** [comment]
Can anyone else replicate this? I can't seem to get it to happen my end

**Comment by mrwhale** [comment]
Bit of a late reply on this one. But can confirm that when I disable RGBW lights, then zone 4 white light isn't in the list anymore. This was after a fresh install. Will upload image once I get to a computer 

I also have Nexus 6, running Android 6. App version 1.7.1
