### ISSUE TITLE
Time Based Events (Lighting Alarms)

### ISSUE THREAD

**Issue by dudeofawesome** [eliotstocker/Light-Controller#6]
I'm not sure if there is a way that we can hook in to the system to detect if an alarm is going off, but if there is a way, we would also need to make a way for the user to select which alarms should trigger the light to go on.

Another thing to think about is getting in contact with the Sleep as Android team and seeing about integrating Light Controller with their app. They already have Phillips HUE integration.

**Comment by eliotstocker** [comment]
I have decided to branch this out into a separate app using the new API (#22) so people who don't need the functionality wont have to have a larger app footprint etc, however i will put i link in the app for it :)

**Comment by eliotstocker** [comment]
I am going to close this and create a new repo for it in the coming days/weeks
