### ISSUE TITLE
Slack Group

### ISSUE THREAD

**Issue by eliotstocker** [eliotstocker/Light-Controller#71]
Hi all, i have created a slack group so we can further discuss issues and development in a more structured way, 

i will invite a number of you (by your github email addresses), but put a note here if you wish to be added or email me with an email address to add you on.

**Comment by eliotstocker** [comment]
@mrwhale you dont have an email that i can access on your github, please let me knwo which email to add :D

@dudeofawesome added you

anyone else?

**Comment by mrwhale** [comment]
Hey @eliotstocker! Nice idea! You can just use my Gmail for this please - harrysibenaler@gmail.com

**Comment by eliotstocker** [comment]
@mrwhale invited you :D

**Comment by jared-jensen** [comment]
@eliotstocker please

**Comment by eliotstocker** [comment]
@jared-jensen invited :)

**Comment by jared-jensen** [comment]
@eliotstocker i didn't get an invite -- where would I look?

**Comment by eliotstocker** [comment]
@jared-jensen sent it to the email address on your github profile, let me know if it didn't come through ill try and invite again

**Comment by eliotstocker** [comment]
ok closing to tidy things up :)
