### ISSUE TITLE
Tasker plugin documentation?

### ISSUE THREAD

**Issue by sanzoghenzo** [eliotstocker/Light-Controller#9]
hi,
I'm trying to make some tasker profiles to work with my mi-light lights, and I used UDP sender to make it work so far. Since I installed your app and found that it has a tasker plugin, I would like to use it in order to have only one app installed, but I didn't get how the plugin works and I can't find any documentation. Should I use it to send only one message or can I batch my commands into one action? Can I pass variables to it?

**Comment by TameOfGroans** [comment]
more documentation could become more better

**Comment by MaximumBonus** [comment]
Tasker documentation and zone control would make this app perfect!

**Comment by eliotstocker** [comment]
I think I mat rewrite the tasker integration a little, using the new api. At which time I'll also write some documentation.

**Comment by eliotstocker** [comment]
Any Tasker heads ot there that fancy trying the tasker implementation using the new super simple API?

**Comment by Gavacac** [comment]
I can give it a try. Can you provide more information?

**Comment by eliotstocker** [comment]
I dont really know much about tasker, but for information on the API check out:
https://github.com/eliotstocker/Light-ControllerAPI

there is an example app and documentation on the API :)
let me know if you need any further info, would you like me to open up a repo and add you too it? @Gavacac or do you want to start your own repo?
